version: '3.8'

services:
  card_db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: card_db
    volumes:
      - card_db_data:/var/lib/postgresql/data

volumes:
  card_db_data:
    driver: local